version: "2"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "<password>"
            ACCEPT_EULA: "Y" 
        volumes:
          - sqlvolume:/var/opt/mssql
        ports:
            - 1433:1433
            - 1434:1434    
            
volumes:
  sqlvolume: