version: '2'
   
services:
    rabbitmq:
        image: rabbitmq:3.8.11-management
        container_name: rabbitmq
        volumes:
            - 'rabbitmq_etc:/etc/rabbitmq/'
            - 'rabbitmq_data:/var/lib/rabbitmq/'
            - 'rabbitmq_log:/var/log/rabbitmq/'
        environment:
            RABBITMQ_DEFAULT_USER: 'admin'
            RABBITMQ_DEFAULT_PASS: '<password>'
        ports:
            - 5672:5672
            - 15672:15672    
            - 1883:1883