// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHomeService.Context;

namespace SmartHomeService.Migrations
{
    [DbContext(typeof(SmartHomeServiceContext))]
    [Migration("20210214123717_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartHomeService.Models.PlantData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastEdited")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("TargetMoisture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlantDatas");
                });

            modelBuilder.Entity("SmartHomeService.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AirMoist")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AirPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AirTemp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlantDataId")
                        .HasColumnType("int");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("SoilMoistPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantDataId");

                    b.ToTable("SensorDatas");
                });

            modelBuilder.Entity("SmartHomeService.Models.SensorData", b =>
                {
                    b.HasOne("SmartHomeService.Models.PlantData", null)
                        .WithMany("SensorDataHistory")
                        .HasForeignKey("PlantDataId");
                });

            modelBuilder.Entity("SmartHomeService.Models.PlantData", b =>
                {
                    b.Navigation("SensorDataHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
